try:
    from _pykpathsea import * 
except:
    import os
    def find_file(filename, kpse_file_format):
        return os.popen("kpsewhich %s" % filename, "r").readline()[:-1]
    kpse_gf_format = ""
    kpse_pk_format = ""
    kpse_any_glyph_format    = ""
    kpse_tfm_format = ""
    kpse_afm_format = ""
    kpse_base_format = ""
    kpse_bib_format = ""
    kpse_bst_format = ""
    kpse_cnf_format = ""
    kpse_db_format = ""
    kpse_fmt_format = ""
    kpse_fontmap_format = ""
    kpse_mem_format = ""
    kpse_mf_format = ""
    kpse_mfpool_format = ""
    kpse_mft_format = ""
    kpse_mp_format = ""
    kpse_mppool_format = ""
    kpse_mpsupport_format = ""
    kpse_ocp_format = ""
    kpse_ofm_format = ""
    kpse_opl_format = ""
    kpse_otp_format = ""
    kpse_ovf_format = ""
    kpse_ovp_format = ""
    kpse_pict_format = ""
    kpse_tex_format = ""
    kpse_texdoc_format = ""
    kpse_texpool_format = ""
    kpse_texsource_format = ""
    kpse_tex_ps_header_format = ""
    kpse_troff_font_format = ""
    kpse_type1_format = ""
    kpse_vf_format = ""
    kpse_dvips_config_format = ""
    kpse_ist_format = ""
    kpse_truetype_format = ""
    kpse_type42_format = ""
    kpse_web2c_format = ""
    kpse_program_text_format = ""
    kpse_program_binary_format = ""
    kpse_miscfonts_format = ""
    kpse_web_format = ""
    kpse_cweb_format = ""
